print("welcome tobrand name generator")
city=input("what is the name of your city you grew up in?")
pet_name=input("what is your pets name?")
smoke_brand=input("what is your cigar name")
print("your brand name is " + city + " "+ pet_name+ ""+smoke_brand)